name: SH Update Target Data

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 21 * * THU'  # Runs every Thursday at 21:00 UTC

permissions:
  contents: write  # Explicitly grant write access

jobs:
  update_target_data:
    runs-on: self-hosted  # Use the self-hosted macOS runner
    env:
      GITHUB_PAT: ${{ secrets.PERSONAL_GITHUB_TOKEN }}  # Use the personal token

    steps:    
      # Step 1: Check out code
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # Step 2: Generate target CSV files
      - name: Generate target CSV files
        run: Rscript scripts/get_target_data.R  
        
      # Step 3: Add new files
      - name: Add new files
        run: git add target-data/
          
      # Step 4: Commit results
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am 'update target data' || echo "No changes to commit"
      
      # Step 5: Push changes with personal token
      - name: Push changes with personal token
        env:
          GITHUB_PAT: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          git push https://${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/ai4castinghub/hospitalization-forecast.git HEAD:main || echo "No changes to commit"
